# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
default_install_hook_types: [pre-commit, commit-msg, pre-push]
default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: trailing-whitespace

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/commitizen-tools/commitizen
    rev: "v2.42.1"
    hooks:
      - id: commitizen
      - id: commitizen-branch
        args: [--rev-range, HEAD]
        stages: [push]

  - repo: local
    hooks:
      - id: format
        name: format
        entry: tox -e format --
        files: "^(src|tests)"
        types_or: [python]
        language: python
        additional_dependencies: [".[dev]"]
      - id: lint
        name: lint
        entry: tox -e lint --
        files: "^src"
        types_or: [python]
        language: python
        additional_dependencies: [".[dev]"]
      - id: test
        name: test
        entry: tox
        always_run: true
        pass_filenames: false
        language: python
        additional_dependencies: [".[dev]"]
        stages: [push]
      - id: security
        name: security
        entry: tox -e security
        always_run: true
        pass_filenames: false
        language: python
        additional_dependencies: [".[dev]"]
        stages: [push]
      - id: docs
        name: docs
        entry: tox -e docs
        always_run: true
        pass_filenames: false
        language: python
        additional_dependencies: [".[dev]"]
        stages: [push]
