name: Deploy docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gh-pages:
    name: Deploy docs on GitHub pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Get pip cache dir
        id: pip-cache
        shell: bash
        run: echo "DIR=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: Get current week number
        id: get-week
        shell: bash
        run: echo "WEEK=$(date +'%V')" >> $GITHUB_OUTPUT
      - name: Pip cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.DIR }}
          key: ${{ runner.os }}-pip-${{ steps.get-week.outputs.WEEK }}-${{ hashFiles('setup.cfg') }}
      - name: Install tox
        run: python -m pip install tox
      - name: Build docs with tox
        run: python -m tox -e docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
